curl -X POST https://vrschool7.herokuapp.com/api/finish_vr_exercise  -H "Content-Type:application/json" -d '{
	"PIN": "4281",
	"VRexerciseID": 22,
	"exerciseVersion": 261,
	"autograde": {
		"passed_items": 6,
		"failed_items": 1,
		"score": 93,
		"comments": "looser"
	}
}'
