curl -X POST http://localhost:8000/api/finish_vr_exercise  -H "Content-Type:application/json" -d '{
	"PIN": "2343",
	"VRexerciseID": 12,
	"exerciseVersion": 281,
	"autograde": {
		"passed_items": 4,
		"failed_items": 3,
		"score": 73,
		"comments": "...to be decided… "
	}
}'
